version: "3.7"

services:

  api:
    build: ./app
    container_name: api
    volumes:
      - php-vender:/app/vendor
    ports:
      - 8000:8000
    depends_on: 
      - db
    links: 
      - db
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "3030:3030"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - api
      - db

  db:
    image: mysql:5.7.28
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=ensibuuko 
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Test@32_
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-data:/var/lib/mysql/
      - ./db:/docker-entrypoint-initdb.d
  
  frontend:
    build: ./frontend
    container_name: frontend
    volumes: 
      - node-modules:/usr/src/app/node_modules
    restart: always
    ports:
      - "8080:8080"
    depends_on: 
      - api

volumes:
  mysql-data:
    driver: local
  php-vender: {}
  node-modules: {}